# Generated by Django 4.2.13 on 2024-12-12 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reportTranslator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('translated_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TextAndAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Store your text here.')),
                ('audio', models.FileField(blank=True, help_text='Upload an MP3 file. This field is optional.', null=True, upload_to='audio_files/', validators=[reportTranslator.models.validate_mp3_file])),
                ('sentences', models.JSONField(blank=True, help_text='Store sentences after splitting text.', null=True)),
                ('final_analysis', models.TextField(blank=True, help_text='Store the analysis result of the text.', null=True)),
                ('diabetes_diagnosis', models.JSONField(blank=True, help_text='Store diabetes diagnosis for each sentence.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the record was last updated.')),
                ('user', models.ForeignKey(help_text='The user who owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='text_and_audio_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
