# Generated by Django 4.2.13 on 2024-12-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportTranslator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinput',
            name='voice_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
