# Generated by Django 4.2.13 on 2024-12-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportTranslator', '0002_textinput_voice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinput',
            name='translated_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
